AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Environment:
    Runtime: nodejs16.x
    MemorySize: 128
    Architectures:
      - x86_64
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Domain:
        DomainName: api.example.com
        CertificateArn: arn:aws:acm:us-east-1:123456789012:certificate/12345678-1234-1234-1234-123456789012
        EndpointConfiguration: REGIONAL
        BasePath: v2
      Cors:
        AllowMethods: "'OPTIONS,GET,POST,DELETE,PATCH,PUT'"
        AllowHeaders: "'Content-Type,Authorization,x-lomi-client,x-lomi-client-version'"
        AllowOrigin: "'*'"
  V1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handleV1
      CodeUri: handlers
      Events:
        UsersGetEvent:
          Type: Api
          Properties:
            Path: /users
            Method: get
